[workspace]
members = [
    "chain",
    "frontend",
    "macros",
    "parser",
    "polyfill",
    "rspec",
    "rspec_lib",
    "rspec_test",
    "vest",
]

default-members = [
    "frontend",
]

exclude = [
    "tools/verusc",
    "verus",
]

resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
