[package]
name = "rspec-test"
version = "0.1.0"
edition = "2021"

[dependencies]
builtin_macros = { path = "../verus/source/builtin_macros" }
builtin = { path = "../verus/source/builtin" }
vstd = { path = "../verus/source/vstd" }
rspec = { path = "../rspec" }
rspec-lib = { path = "../rspec_lib" }
