name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Format
      run: rustup component add rustfmt && cargo fmt --check

  verified-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build debug
      run: source tools/activate.sh && cargo verus build
    - name: Build debug with tracing
      run: source tools/activate.sh && cargo verus build --features trace
    - name: Build release
      run: source tools/activate.sh && cargo verus build --release
    - name: Build release with verified-crypto feature
      run: source tools/activate.sh && cargo verus build --release --features verified-crypto
    - name: Test
      run: source tools/activate.sh && cargo test --workspace

  unverified-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build debug
      run: cargo build
    - name: Build release
      run: cargo build --release
    - name: Build release with verified-crypto feature
      run: cargo build --release --features verified-crypto

  update-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Compile docs
      run: ./tools/gen_docs.sh
    - name: Upload docs
      uses: actions/upload-pages-artifact@v3
      with:
        path: target/doc
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
